### ISSUE TITLE
Configure RPi / Crankshaft

### ISSUE THREAD

**Issue by jacoqq** [laurynas/volvo_crankshaft#11]
Hi, 
Can anyone please tell me how to do:
> Unlock readonly Crankshaft filesystem using csmt command line utility.
Copy files from [crankshaft/](https://github.com/laurynas/volvo_crankshaft/blob/main/crankshaft) to RPi using SSH or just create them via the terminal. Place files under appropriate system folders and make /opt/service_volvo_crankshaft.sh executable.

I'm pretty bad in linux CLI, and when i write "systemctl enable volvo_crankshaft"  i get "Failed to enable unit: Unit file volvo>crankshaft.service does not exist. Yes, every files is copied, so i think messed up something. 
I'll be much apritiated for any help, especially for full code lines :)

**Comment by laurynas** [comment]
Hey, I suggest to ask in Crankshaft GitHub:
https://github.com/opencardev/crankshaft/discussions
or
https://github.com/opencardev/crankshaft/issues
