### ISSUE TITLE
sharing of your volvo crankshaft project

### ISSUE THREAD

**Issue by aeonSolutions** [laurynas/volvo_crankshaft#12]
Hi there @laurynas 
great project.
Just to let you know I'm sharing your project on my own Volvo project here on GitHub:
[https://github.com/aeonSolutions/AeonLabs-AI-Volvo-MKII-Open-Hardware/wiki/RTI-Display](https://github.com/aeonSolutions/AeonLabs-AI-Volvo-MKII-Open-Hardware/wiki/RTI-Display)

**Comment by laurynas** [comment]
Hey @aeonSolutions! Thanks! Your project looks cool! ;)

**Comment by aeonSolutions** [comment]
Thank you. 
Just finished today the OPEN ECU . Next i'll be designing and prototyping the front door modules and later the instruments cluster.
